name       : incidenceeditor
version    : 24.01.95
release    : 74
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/incidenceeditor-24.01.95.tar.xz : aa14d960c293d392785cf2cb75f7f2557c53697c7b308b56a7421c771c7d7537
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM incidence editor
description: |
    KDE PIM incidence editor.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - calendarsupport-devel
    - eventviews-devel
    - kdiagram-devel
    - kf6-kcontacts-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmailtransport-devel
    - ktextaddons-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
