name       : breeze-gtk-theme
version    : 5.93.0
release    : 96
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/breeze-gtk-5.93.0.tar.xz : 4d7e517399d77ed4894d029b4fd3b46b7fca297fd78b90f4626e9afea2e30853
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt6Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
