name       : kanagram
version    : 24.01.95
release    : 73
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kanagram-24.01.95.tar.xz : 0594e408b62158058cfc54b93356052d901c39923965ba359df194c610db62aa
homepage   : https://kde.org/applications/education/org.kde.kanagram
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6TextToSpeech)
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-kxmlgui-devel
    - kf6-sonnet-devel
    - libkeduvocdocument-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache

    # remove doc
    rm -rf $installdir/usr/share/doc
