name       : gom
version    : 0.5.5
release    : 15
source     :
    - https://download.gnome.org/sources/gom/0.5/gom-0.5.5.tar.xz : ad61f05af2317a7ab1771fcfa816989fbba3b18957d2e0b5dede9ef45f09b534
homepage   : https://gitlab.gnome.org/GNOME/gom
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GObject Data Mapper
description: |
    Gom provides an object mapper from GObjects to SQLite. It helps you write applications that need to store structured data as well as make complex queries upon that data.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sqlite3)
    - python-setuptools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
