name       : gnote
version    : '49.0'
release    : 35
source     :
    - https://download.gnome.org/sources/gnote/49/gnote-49.0.tar.xz : 19751a2f237729bf9f48495540a35e346e45c1ba1b016db9cb754d45eced0a5d
homepage   : https://gitlab.gnome.org/GNOME/gnote
license    : GPL-3.0-or-later
component  : office.notes
summary    : A simple and easy to use desktop note-taking application
description: |
    Gnote is a simple note-taking application for GNOME desktop environment. It allows you to capture your ideas, link them together using WikiWiki-style links, group together in notebooks and some extra features for everyday use.
optimize   :
    - lto
builddeps  :
    - pkgconfig(glibmm-2.68)
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-4.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
