name       : cjs
version    : '128.1'
release    : 1
source     :
    - https://github.com/linuxmint/cjs/archive/refs/tags/128.1.tar.gz : 20e59f7402f960fbba184b2eb2cdee60e316554fd771bf4d5598ec5e3b9d1002
homepage   : https://github.com/linuxmint/cjs
license    :
    - LGPL-2.0-or-later
    - MIT
component  : dekstop.library
summary    : The Cinnamon Javascript interpreter
description: |
    The Cinnamon Javascript interpreter
builddeps  :
    - pkgconfig(cairo-svg)
    - pkgconfig(mozjs-128)
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
