name       : gnome-chess
version    : '49.2'
release    : 38
source     :
    - https://download.gnome.org/sources/gnome-chess/49/gnome-chess-49.2.tar.xz : c40a0004a473fe749ac2fa4fad98db64118d18f9fd9ac02eecfa364f03dbe9b0
homepage   : https://gitlab.gnome.org/GNOME/gnome-chess
license    : GPL-2.0-or-later
component  : games.strategy
summary    : GNOME Chess Game
description: |
    GNOME Chess is a 2D chess game, where games can be played between a combination of human and computer players. GNOME Chess detects known third party chess engines for computer players.
optimize   :
    - lto
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - gnuchess
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
