name       : neohtop
version    : 1.1.2
release    : 1
source     :
    - https://github.com/Abdenasser/neohtop/archive/refs/tags/v1.1.2.tar.gz : 6415efdaadc88b3b0c02cd7c3c18a39abd91f01475be72f44ddd5effd112e905
homepage   : https://abdenasser.github.io/neohtop/
license    : MIT
component  : system.utils
summary    : A beautiful, lightning-fast cross-platform system monitor.
description: |
    A modern, cross-platform system monitor built on top of Svelte, Rust, and Tauri.
networking : yes
builddeps  :
  - pkgconfig(libsoup-3.0)
  - pkgconfig(webkit2gtk-4.1)
  - nodejs
  - rust
build      : |
  npm install
  npm run tauri build
install    : |
  install -Dm00755 src-tauri/target/release/NeoHtop $installdir/usr/bin/neohtop
  install -Dm00644 src-tauri/icons/icon.png $installdir/usr/share/pixmaps/neohtop.png
  install -Dm00644 $pkgfiles/neohtop.desktop $installdir/usr/share/applications/neohtop.desktop
