name       : kdenetwork-filesharing
version    : 24.01.95
release    : 61
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdenetwork-filesharing-24.01.95.tar.xz : b11cc634df2ab202d09005c1b20e54259f4982da9e4724688f0dc34ef4523aa6
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kf6-kauth-devel
    - kf6-kdeclarative-devel
    - kf6-kio-devel
    - qcoro-qt6-devel
setup      : |
    %cmake_kf6 -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
