name       : kpmcore
version    : 24.01.95
release    : 39
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kpmcore-24.01.95.tar.xz : 4d4fcf92b86ce6d60e05fd5cc16270f828b2b31ac495411134f372e3efb01854
homepage   : https://invent.kde.org/system/kpmcore
license    : GPL-3.0-or-later
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt6-1)
    - kauth-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-kwidgetsaddons-devel
    - qca-qt6-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
