name       : kleopatra
version    : 24.01.95
release    : 68
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kleopatra-24.01.95.tar.xz : bfa0c57975cd9e8ab7b0efb7e39efa18003957251ec387c87b9f7429707b150e
homepage   : https://kde.org/applications/utilities/org.kde.kleopatra
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(libassuan)
    - gpgme-qt-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kitemmodels-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ktextwidgets-devel
    - kf6-kwindowsystem-devel
    - kf6-kxmlgui-devel
    - kmbox-devel
    - kmime-devel
    - libboost-devel
    - libkleo-devel
    - mimetreeparser-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
