name       : gnome-console
version    : '49.1'
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-console/49/gnome-console-49.1.tar.xz : fca39fd041e05ee7ca6d2a5c82001937d02ae1513f3f3651bd37ae0e2ef66e3e
homepage   : https://apps.gnome.org/Console/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Terminal Emulator
description: |
    A simple user-friendly terminal emulator for the GNOME desktop
optimize   :
    - lto
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(vte-2.91-gtk4)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
