name       : kwalletmanager
version    : 24.01.95
release    : 72
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kwalletmanager-24.01.95.tar.xz : 0e338cf413f105b6f2ef9c351a7c8cf93b91c19237ba832dfa56e1a59036487d
homepage   : https://apps.kde.org/kwalletmanager5/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
optimize   : lto
builddeps  :
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ktextwidgets-devel
    - kf6-kwallet-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
