name       : kicad-templates
version    : 9.0.6
release    : 17
source     :
    - https://gitlab.com/kicad/libraries/kicad-templates/-/archive/9.0.6/kicad-templates-9.0.6.tar.gz : 93eddbf10ced61364387a9bb37e589c7fcf2ed1635239244f8bc51428c0d40a5
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
