name       : kclock
version    : 24.01.95
release    : 2
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kclock-24.01.95.tar.xz : edd0ecf55550e4554d1a84e8dda2b279aa669a0edd5e323bfb4a7ae411a5a2f9
homepage   : https://apps.kde.org/kclock
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Clock app for KDE Plasma
description: |
    A convergent clock for KDE Plasma desktop and mobile
    Features
        - Alarms
        - Stopwatch
        - World Clocks
        - Timers
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6DBus)
    - pkgconfig(Qt6Gui)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6Test)
    - pkgconfig(Qt6Widgets)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kirigami-addons-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - libplasma-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
