name       : polkit-kde-agent
version    : 5.93.0
release    : 92
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/polkit-kde-agent-1-5.93.0.tar.xz : abb57495965a26eeb6342b4c4943b54f3159dc1031356909703488f4ff374a7f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-kiconthemes-devel
    - kf6-kwidgetsaddons-devel
    - kf6-kwindowsystem-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
