name       : kmail
version    : 24.01.95
release    : 79
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kmail-24.01.95.tar.xz : 9693862724da263af59cb948aa61373539c20a3621aa61358a51c5add99bdc66
homepage   : https://apps.kde.org/kmail2/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-only
component  : network.mail
summary    : Email client, supporting POP3 and IMAP mailboxes
description: |
    KMail is the email component of Kontact, the integrated personal information manager from KDE.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(ldap)
    - akonadi-search-devel
    - kcalutils-devel
    - kf6-kcalendarcore-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-kparts-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kuserfeedback-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmailtransport-devel
    - kontactinterface-devel
    - ktextaddons-devel
    - ktnef-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - pimcommon-devel
    - qtkeychain-qt6-devel
rundeps    :
    - akonadi-import-wizard
    - kdepim-runtime
    - kleopatra
    - kmail-account-wizard
    - pim-data-exporter
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
