name       : kaccounts-integration
version    : 24.01.90
release    : 62
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/kaccounts-integration-24.01.90.tar.xz : 458ec171b6355fd02ebf050f50fa07f831fac73ff45451017f83215b42f68f59
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt6)
    - pkgconfig(signond)
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kio-devel
    - kf6-kwallet-devel
    - qcoro-qt6-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
    - devel :
        - signond-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
