name       : cinnamon-settings-daemon
version    : 6.6.3
release    : 1
source     :
    - https://github.com/linuxmint/cinnamon-settings-daemon/archive/refs/tags/6.6.3.tar.gz : c55cd5037adeb05a25c21fd4a9c03bd147e2917727c189a58e79c9dbfcaf489c
homepage   : https://github.com/linuxmint/cinnamon-settings-daemon
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : dekstop.library
summary    : The settings daemon for the Cinnamon desktop.
description: |
    The settings daemon for the Cinnamon desktop.
builddeps  :
    - pkgconfig(cinnamon-desktop)
    - pkgconfig(colord)
    - pkgconfig(cups)
    - pkgconfig(cvc)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnomekbd)
    - pkgconfig(libnotify)
    - pkgconfig(nss)
    - pkgconfig(upower-glib)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
