name       : kdegraphics-mobipocket
version    : 24.01.95
release    : 72
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdegraphics-mobipocket-24.01.95.tar.xz : 46fe3b47b36f61c15484372a1d678da4b1343414be9d461a39668a315bc705c8
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Core5Compat)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
