name       : grantleetheme
version    : 24.01.95
release    : 69
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/grantleetheme-24.01.95.tar.xz : 9156f13722b055d359488488fe73f8b9a71e7238cf93687112085a34839b2054
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : GrantleeTheme library provides a class for loading theme packages containing sets of templates
description: |
    GrantleeTheme library provides a class for loading theme packages containing sets of templates.
builddeps  :
    - kf6-kguiaddons-devel
    - kf6-ki18n-devel
    - kf6-kiconthemes-devel
    - kf6-knewstuff-devel
    - kf6-kservice-devel
    - kf6-ktexttemplate-devel
    - kf6-kxmlgui-devel
rundeps    :
    - devel :
        - kf6-ktexttemplate-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
