name       : konversation
version    : 24.01.95
release    : 39
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/konversation-24.01.95.tar.xz : dc65ddb63bfa7fb0e8b9997226781297a4aaca108365caf483af17a35f260cbf
homepage   : https://konversation.kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.irc
summary    : User-friendly IRC client built on the KDE Platform
description: |
    Konversation is a user-friendly Internet Relay Chat (IRC) client built on the KDE Platform.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Multimedia)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kidletime-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-kparts-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ktextwidgets-devel
    - kf6-kwallet-devel
    - qca-qt6-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
