name       : gnome-calculator
version    : 49.1.1
release    : 45
source     :
    - https://download.gnome.org/sources/gnome-calculator/49/gnome-calculator-49.1.1.tar.xz : 840d3459ed69f2787a9669f96f6b3f9eff16cb486900c719ac252c424563463d
homepage   : https://apps.gnome.org/Calculator/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Perform arithmetic, scientific or financial calculations
description: |
    A tool for calculating mathematical equations. Uses standard mathematical notation where possible (so users do not have to learn the application when they already know maths). Easy enough to use for simple maths (add, subtract, multiply, divide). Powerful enough for mid-level mathematics (though not at the expense of being easy for simple mathematics).
optimize   :
    - lto
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtksourceview-5)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - blueprint-compiler
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
