name       : ksystemlog
version    : 24.01.95
release    : 40
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/ksystemlog-24.01.95.tar.xz : ea391d1a3556b384909f82a00216835986d0ccbc6e1d79418e222d9956ab30e3
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc

    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/pixmaps/utilities-log-viewer.png
