name       : evolution
version    : 3.58.1
release    : 86
source     :
    - https://download.gnome.org/sources/evolution/3.58/evolution-3.58.1.tar.xz : 03d8d0cccd102aa1a73c31d9e2f374cb3db83acddfc1126c9186af63da6cbecc
homepage   : https://gnome.pages.gitlab.gnome.org/evolution/help/
license    : LGPL-2.1-or-later
component  : network.mail
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gweather4)
    - pkgconfig(ldap)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libcmark)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(nss)
    - pkgconfig(shared-mime-info)
    - pkgconfig(webkit2gtk-4.1)
    - at-spi2-devel
    - gtk-doc
    - highlight
    - itstool
rundep     :
    - highlight
setup      : |
    %cmake_ninja \
        -DENABLE_AUTOAR=ON \
        -DENABLE_GTK_DOC=ON \
        -DENABLE_TEXT_HIGHLIGHT=ON \
        -DENABLE_PST_IMPORT=OFF \
        -DENABLE_YTNEF=OFF \
        -DLIB_INSTALL_DIR=%libdir% \
        -DSYSCONF_INSTALL_DIR=/etc \
        -DWITH_OPENLDAP=ON \
        -DWITH_GWEATHER4=ON \
        -DENABLE_WEATHER=ON .
build      : |
    %ninja_build
install    : |
    %ninja_install
