name       : eventviews
version    : 24.01.95
release    : 72
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/eventviews-24.01.95.tar.xz : e58c5fb069d5a5abb687e5856aa01732cc8d72f1e9024463fb5fe50cf3365534
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - kcalutils-devel
    - kf6-kcompletion-devel
    - kf6-kcontacts-devel
    - kdiagram-devel
    - kf6-kguiaddons-devel
    - kf6-kholidays-devel
    - kf6-kiconthemes-devel
    - kidentitymanagement-devel
    - kmime-devel
    - kf6-kservice-devel
    - kf6-kxmlgui-devel
    - libkdepim-devel
rundeps    :
    - devel :
        - kcalutils-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
