name       : gnome-epub-thumbnailer
version    : '1.8'
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-epub-thumbnailer/1.8/gnome-epub-thumbnailer-1.8.tar.xz : f90619d58c69902f2eff57b9f0042b4737861083f475921a310fecc612fca017
homepage   : https://gitlab.gnome.org/GNOME/gnome-epub-thumbnailer
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Thumbnailer for EPub and MOBI books
description: |
    Thumbnailer for EPub and MOBI books
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libarchive)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
