name       : kpkpass
version    : 24.01.95
release    : 57
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kpkpass-24.01.95.tar.xz : e366f5b8becf40c1325e8fd196130466dc24dc6d4651e78cb9df7a6961423203
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - extra-cmake-modules
    - kf6-karchive-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
