name       : abiword
version    : 3.0.7
release    : 35
source     :
    - https://gitlab.gnome.org/World/AbiWord/-/archive/release-3.0.7/AbiWord-release-3.0.7.tar.bz2 : 19099c5cc6022efba50cebf0f081a21afdb5358256b4ea9b51c735968132f362
homepage   : https://gitlab.gnome.org/World/AbiWord
license    : GPL-2.0-or-later
component  : office
summary    : Free lightweight word processor similar to Microsoft Word
description: |
    Abiword is a free and lightweight word processor similar to Microsoft Word, allowing many of the same functions while being better on resources.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(enchant)
    - pkgconfig(fribidi)
    - pkgconfig(gspell-1)
    - pkgconfig(libgcrypt)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libturbojpeg)
    - pkgconfig(wv-1.0)
    - autoconf-archive
    - intltool
    - libboost-devel
    - libtool-devel
clang      : false
libsplit   : false
setup      : |
    %autogen \
        --enable-clipart \
        --enable-emacs-keybinding \
        --enable-templates \
        --enable-vi-keybinding \
        --without-evolution-data-server \
        --with-goffice
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/applications/{abiword.desktop,com.abisource.AbiWord.desktop}

    # Don't install metainfo to obsolete path
    install -Dm00644 $installdir/usr/share/appdata/abiword.appdata.xml \
    $installdir/usr/share/metainfo/abiword.metainfo.xml
    rm -rv $installdir/usr/share/appdata
