name       : kdepim-addons
version    : 24.01.95
release    : 69
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdepim-addons-24.01.95.tar.xz : f1cde197de1e28a6f13f4e65df170fc45ef1e2bdf960fa59f74fdbc6eb26d235
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Addons for KDE PIM applications
description: |
    Addons for KDE PIM applications including akregator, kaddressbook, kmail and korganizer.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(libmarkdown)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-import-wizard-devel
    - akonadi-notes-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kaddressbook-devel
    - kf6-kcontacts-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kguiaddons-devel
    - kf6-kholidays-devel
    - kf6-kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitinerary-devel
    - kmailtransport-devel
    - kontactinterface-devel
    - kf6-kparts-devel
    - kpkpass-devel
    - ktextaddons-devel
    - ktnef-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
    - kf6-prison-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
