name       : dolphin-plugins
version    : 24.01.95
release    : 67
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/dolphin-plugins-24.01.95.tar.xz : ab9ed7bb92e27fde0a74e764254a433689487552a9e3260436e2a4c989e8f0d7
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - dolphin-devel
    - kf6-ktexteditor-devel
    - kf6-ktextwidgets-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
