name       : libkmahjongg
version    : 24.01.95
release    : 50
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libkmahjongg-24.01.95.tar.xz : ea56b4e32db11b24f4de17965c4b8da005b219544287d9482ae5b9cbab32b0bf
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt6Svg)
    - kf6-kcompletion-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-kwidgetsaddons-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
