name       : kdepim-runtime
version    : 24.01.95
release    : 77
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdepim-runtime-24.01.95.tar.xz : 5c810d7127929eaf8a2653cfc9fe88d22628bc7b496f726c0b5722f5e3c848a2
homepage   : https://community.kde.org/PIM
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Runtime components for Akonadi
description: |
    Contains the Akonadi resources from kdepim which can be used without the applications in kdepim.
builddeps  :
    - pkgconfig(Qt6NetworkAuth)
    - pkgconfig(Qt6TextToSpeech)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(libcurl)
    - pkgconfig(libsasl2)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - kcalutils-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kdav-devel
    - kf6-kdoctools-devel
    - kf6-kholidays-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kf6-kio-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kpimtextedit-devel
    - kf6-kwallet-devel
    - ktextaddons-devel
    - libical-devel
    - libkdepim-devel
    - libkgapi-devel
    - libkolabxml-devel
    - pimcommon-devel
    - qca-qt6-devel
    - qtkeychain-qt6-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
