name       : libkdepim
version    : 24.01.95
release    : 73
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libkdepim-24.01.95.tar.xz : e73257f673a9d4aabc50996c5dab2156a42795edcb1be44e488636f8f9238719
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kf6-kcompletion-devel
    - kf6-kconfigwidgets-devel
    - kf6-ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
