name       : ktnef
version    : 24.01.95
release    : 68
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/ktnef-24.01.95.tar.xz : f4bfb537ae606eb88ac4b4137763218b102adbdeff0058ea33784e5060b2a4f7
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kf6-kcalendarcore-devel
    - kcalutils-devel
    - kf6-kcontacts-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
