name       : messagelib
version    : 24.01.95
release    : 82
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/messagelib-24.01.95.tar.xz : cb115d772f06efcef19224237d75bc2a5d0d7ca0df7c4d472b824a134b33137f
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - qca-qt6-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - kf6-karchive-devel
    - kf6-kcontacts-devel
    - kf6-kdbusaddons-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kf6-kio-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - ktextaddons-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - pimcommon-devel
    - kf6-syntax-highlighting-devel
    - kf6-kxmlgui-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
