name       : kitinerary
version    : 24.01.95
release    : 76
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kitinerary-24.01.95.tar.xz : 73c787fd28a7ca3f7d47f1568a43602d6457d213239d8d6680c17fa1b03edb76
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(poppler)
    - pkgconfig(zxing)
    - kf6-karchive-devel
    - kf6-kcalendarcore-devel
    - kf6-kcontacts-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
