name       : flatpak-kcm
version    : 5.93.0
release    : 6
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/flatpak-kcm-5.93.0.tar.xz : c6f6762647e280734235b04dfe6c08456cb48b266132ca254a084cf7785c988d
homepage   : https://invent.kde.org/plasma/flatpak-kcm
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Flatpak Permissions Management KCM
description: |
    Flatpak Permissions Management KCM
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Svg)
    - pkgconfig(flatpak)
    - extra-cmake-modules
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kdeclarative-devel
    - kf6-ki18n-devel
    - kf6-kitemmodels-devel
clang      : yes
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/flatpak-discover.svg $installdir/usr/share/icons/hicolor/scalable/apps/flatpak-discover.svg
