name       : libkomparediff2
version    : 24.01.95
release    : 72
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libkomparediff2-24.01.95.tar.xz : d78369e465b70315f35e0a6981c6bf1b527906c44c0a18667676d5f9eb43838f
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - kf6-kio-devel
    - kf6-kxmlgui-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
