name       : kmail-account-wizard
version    : 24.01.95
release    : 73
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kmail-account-wizard-24.01.95.tar.xz : 8acfd11352a091b5d70bd4baf6b63b0313a00dbb1f3e1ef30f3ea6a75ea436d3
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KMail Account Wizard
description: |
    An application which assists you with the configuration of accounts in KMail.
builddeps  :
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - gpgme-qt-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kpimtextedit-devel
    - kross-devel
    - ktextaddons-devel
    - kf6-ktexteditor-devel
    - kf6-kwallet-devel
    - libkdepim-devel
    - libkleo-devel
    - pimcommon-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
