name       : knotes
version    : 24.01.95
release    : 71
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/knotes-24.01.95.tar.xz : ad1b908f234ec3ebc5d51655fb178a970b10621156f389bad9bf64778560de17
homepage   : https://kde.org/applications/utilities/org.kde.knotes
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.notes
summary    : Full featured note application
description: |
    KNotes aims to be a useful and full featured notes application for the KDE project. It tries to be as fast and lightweight as possible although including some advanced features.
builddeps  :
    - pkgconfig(x11)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - kf6-kcalendarcore-devel
    - kcalutils-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kcrash-devel
    - kf6-kdnssd-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kimap-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kontactinterface-devel
    - kf6-kparts-devel
    - kf6-kstatusnotifieritem-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
