name       : kdegraphics-thumbnailers
version    : 24.01.95
release    : 67
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdegraphics-thumbnailers-24.01.95.tar.xz : 655d773c01584d85ac9db506f34341066f60e3e9725a9f1e9da40f15976fe1b0
homepage   : https://apps.kde.org/kdegraphics_thumbnailers/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Core)
    - kf6-karchive-devel
    - kdegraphics-mobipocket-devel
    - kf6-kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
