name       : libvte
version    : 0.82.1
release    : 80
source     :
    - https://download.gnome.org/sources/vte/0.82/vte-0.82.1.tar.xz : 79376d70402d271e2d38424418e1aea72357934d272e321e3906b71706a78e3a
homepage   : https://gitlab.gnome.org/GNOME/vte
license    : LGPL-3.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(liblz4)
    - pkgconfig(libpcre2-8)
    - fast-float
    - gi-docgen
    - gperf
    - libiconv-devel
    - vala
rundeps    :
    - devel :
        - pcre2-devel
patterns   :
    - docs :
        - /usr/share/doc/*
setup      : |
    %patch -p1 -i $pkgfiles/0001-app-Make-build-configurable.patch

    %meson_configure \
                     -Dapp=false \
                     -Ddocs=true \
                     -Dgtk4=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
