name       : kicad-symbols
version    : 9.0.6
release    : 18
source     :
    - https://gitlab.com/kicad/libraries/kicad-symbols/-/archive/9.0.6/kicad-symbols-9.0.6.tar.gz : b1dc389dafe81029aa348a5731f22074945c50f22809f09e928ebfa6a1aeccbe
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad schematic symbol libraries
description: |
    Official KiCad schematic symbol libraries.
setup      : |
    %cmake
install    : |
    %make_install
