name       : ypkg
version    : '31'
release    : 175
source     :
    - git|https://github.com/getsolus/ypkg.git : a33039418efdabffb4e5f6883f6615a2b7fe30db
homepage   : https://github.com/getsolus/ypkg
license    : GPL-3.0-or-later
component  : system.devel
summary    : Modern, declarative, structured build format
description: |
    ypkg is the build tool of choice for Solus. Simply put, it is a tool to convert a build process into a packaging operation.
mancompress: yes
rundeps    :
    - fakeroot
    - pyyaml
    - python-eopkg
    - ruamel_yaml
build      : |
    %python3_setup
install    : |
    %python3_install
    # These are going to be replaced by ypkg-tools
    install -Ddm00755 $installdir/usr/share/ypkg
    ln -sv ../../bin/yupdate $installdir/usr/share/ypkg/yupdate.py
    ln -sv ../../bin/ybump $installdir/usr/share/ypkg/ybump.py
