name       : glibmm-2.68
version    : 2.86.0
release    : 9
source     :
    - https://download.gnome.org/sources/glibmm/2.86/glibmm-2.86.0.tar.xz : 39c0e9f6da046d679390774efdb9ad564436236736dc2f7825e614b2d4087826
homepage   : https://gtkmm.org
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : C++ bindings to GLib (2.68 ABI)
description: |
    C++ bindings to GLib (2.68 ABI)
builddeps  :
    - pkgconfig(sigc++-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
