name       : libkexiv2
version    : 24.01.95
release    : 73
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libkexiv2-24.01.95.tar.xz : c405da05f219c1c56b18cb7511654453d2e11999fa5af54cd61e9f1b46ca8889
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
optimize   : lto
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(exiv2)
    - pkgconfig(libssh)
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
