name       : kfind
version    : 24.01.95
release    : 30
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kfind-24.01.95.tar.xz : 641029492ce9ee4f5d26a81d20c4fc7dad782d014f677b7c92f66ae4abe8d3e1
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kio-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rv $installdir/usr/share/doc
