name       : gdm
version    : '49.1'
release    : 81
source     :
    - https://download.gnome.org/sources/gdm/49/gdm-49.1.tar.xz : 69da5d1319dc2c68adf5cd394ad59bec99bb2e24f284045a1bb4acd7740044e5
homepage   : https://projects.gnome.org/gdm/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Graphical Display Manager
description: |
    A graphical login manager for your desktop, integrated within the GNOME desktop environment
optimize   :
    - lto
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(ply-boot-client)
    - itstool
rundeps    :
    - gnome-shell
    - linux-driver-management-gdm-integration
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    %patch -p1 -i $pkgfiles/0001-Source-usr-share-defaults-etc-xprofile.patch
    %patch -p1 -i $pkgfiles/0001-Support-stateless-dir-for-xinitrc.d-files.patch
    %patch -p1 -i $pkgfiles/0001-Xsession-Don-t-start-ssh-agent-by-default.patch

    %meson_configure \
        -Dat-spi-registryd-dir=%libdir%/at-spi2/core \
        -Ddbus-sys=/usr/share/dbus-1/system.d \
        -Ddefault-pam-config=lfs \
        -Dgdm-xsession=true \
        -Dpam-mod-dir=%libdir%/security \
        -Drun-dir=/run/gdm
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Use factory mechanism to ensure GDM config is present
    install -D -m 00644 $pkgfiles/client.conf $installdir/usr/share/factory/var/lib/gdm/.config/pulse/client.conf

    # Ensure we have sysusers + tmpfiles
    install -D -m 00644 $pkgfiles/gdm.tmpfiles $installdir/%libdir%/tmpfiles.d/gdm.conf

    install -Dm00644 $pkgfiles/gdm.group $installdir/%libdir%/userdb/gdm.group
    ln -s gdm.group $installdir/%libdir%/userdb/21.group
    install -Dm00644 $pkgfiles/gdm.user $installdir/%libdir%/userdb/gdm.user
    ln -s gdm.user $installdir/%libdir%/userdb/21.user

    # Pre-enable gdm
    ln -sv gdm.service $installdir/usr/lib/systemd/system/display-manager.service

    # fix PAM
    rm -rfv $installdir/etc/pam.d
    install -dm00755 $installdir/usr/share/defaults/etc/pam.d
    install -m00644 $pkgfiles/pam.d/* -t $installdir/usr/share/defaults/etc/pam.d

    # Cleanup
    find $installdir -type d -empty -print -delete
conflicts  :
    - lightdm
    - lightdm-gtk-greeter
    - sddm
    - slick-greeter
