name       : kldap
version    : 24.01.95
release    : 72
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kldap-24.01.95.tar.xz : 86ebe1a37ec207864a33bd35b080fccd23967b5a10da720bb7c2d0208a2c7f5f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(ldap)
    - pkgconfig(libsasl2)
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - qtkeychain-qt6-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
