name       : nautilus-python
version    : 4.1.0
release    : 22
homepage   : https://gitlab.gnome.org/GNOME/nautilus-python
source     :
    - https://download.gnome.org/sources/nautilus-python/4.1/nautilus-python-4.1.0.tar.xz : fc4a448bccb1a09b68865409b9e2aed171d28a2d5ac80f7be44f5fcca84ee0c1
license    : GPL-2.0-or-later
component  : desktop
summary    : Nautilus-python enables Python extentions in Nautilus
description: |
    These are unstable bindings for the nautilus extension library introduced in Gnome 2.6.
builddeps  :
    - pkgconfig(libnautilus-extension-4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
