name       : kpat
version    : 24.01.95
release    : 57
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kpat-24.01.95.tar.xz : 484cd7db8a5ba418a59fd400884a069919e69c479b7216ba800ed6bc25b713ad
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
homepage   : https://kde.org/applications/games/org.kde.kpat
component  : games.card
summary    : KDE patience game
description: |
    KDE patience game.
libsplit   : no
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Svg)
    - pkgconfig(libblack-hole-solver)
    - pkgconfig(libfreecell-solver)
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
