name       : plasma-systemmonitor
version    : 5.93.0
release    : 30
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/plasma-systemmonitor-5.93.0.tar.xz : 0065593dbaec47a993edcd916e30367e20523d00f0a30293e79d842e07cca989
homepage   : https://kde.org/plasma-desktop
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
libsplit   : no
builddeps  :
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - kirigami-addons-devel
    - libksysguard-devel
rundeps    :
    - kf6-kirigami
    - ksystemstats
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
