name       : kio-gdrive
version    : 24.01.95
release    : 48
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kio-gdrive-24.01.95.tar.xz : a9e127e17edca84b12937da38ef506134ea6e2c8187845802fe7dd792bf98d5f
homepage   : https://apps.kde.org/kio_gdrive/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt6)
    - kaccounts-integration-devel
    - kf6-kcalendarcore-devel
    - kf6-kcontacts-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-purpose-devel
    - libkgapi-devel
    - qtkeychain-qt6-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
