name       : drkonqi
version    : 5.93.0
release    : 89
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/drkonqi-5.93.0.tar.xz : 66218cf3934c22c7fa414fc7503e7d2fa1801586b50cfeca51fbccc50de8e932
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
networking : yes
builddeps  :
    - pkgconfig(Qt6Quick)
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdeclarative-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kuserfeedback-devel
    - kf6-kwallet-devel
    - kf6-syntax-highlighting-devel
    - polkit-qt-1-qt6-devel
    - python-distro
    - python-psutil
rundep     :
    - kf6-kcmutils
    - kf6-kirigami
    - gdb
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6 -DWITH_GDB12=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
