name       : libgtk-4
version    : 4.20.2
release    : 53
source     :
    - https://download.gnome.org/sources/gtk/4.20/gtk-4.20.2.tar.xz : 5e8240edecafaff2b8baf4663bdceaa668ef10a207bee4d7f90e010e10bddc5c
homepage   : https://www.gtk.org/
license    : LGPL-2.0-or-later
component  :
    - desktop.gtk
    - demos : desktop.gtk
    - icon-browser : desktop.gtk
summary    :
    - libgtk-4 contains the libraries used for creating graphical user interfaces and applications.
    - demos : Demonstrations of major GTK4 features.
    - icon-browser : Sample application to graphically search well known GTK4 icon names.
description:
    - libgtk-4 contains the libraries used for creating graphical user interfaces and applications.
    - demos : Demonstrations of major GTK4 features.
    - icon-browser : Sample application to graphically search well known GTK4 icon names.
optimize   :
    - lto
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cloudproviders)
    - pkgconfig(colord)
    - pkgconfig(cups)
    - pkgconfig(epoxy)
    - pkgconfig(graphene-1.0)
    - pkgconfig(gstreamer-player-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libavformat)
    - pkgconfig(libcrypt)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pango)
    - pkgconfig(shaderc)
    - pkgconfig(tinysparql-3.0)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - python-gobject
    - sassc
    - vulkan-headers
rundeps    :
    - devel :
        - vulkan-headers
setup      : |
    %meson_configure \
        -Dbuild-tests=false \
        -Dcloudproviders="enabled" \
        -Dcolord="enabled" \
        -Ddocumentation=false \
        -Dintrospection="enabled" \
        -Dman-pages=false \
        -Doptimization=3 \
        -Dtracker=enabled \
        -Dvulkan="enabled"
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/bin/gtk4-demo*
        - /usr/bin/gtk4-node*
        - /usr/bin/gtk4-print*
        - /usr/bin/gtk4-widget*
        - /usr/share/applications/org.gtk.Demo4*
        - /usr/share/applications/org.gtk*.NodeEditor*
        - /usr/share/applications/org.gtk.PrintEditor4*
        - /usr/share/applications/org.gtk.WidgetFactory4*
        - /usr/share/glib-2.0/schemas/org.gtk.Demo4*
        - /usr/share/icons/hicolor/*/apps/org.gtk.Demo4*
        - /usr/share/icons/hicolor/*/apps/org.gtk*.NodeEditor*
        - /usr/share/icons/hicolor/*/apps/org.gtk.PrintEditor4*
        - /usr/share/icons/hicolor/*/apps/org.gtk.WidgetFactory4*
        - /usr/share/metainfo/org.gtk.Demo4*
        - /usr/share/metainfo/org.gtk*.NodeEditor*
        - /usr/share/metainfo/org.gtk.PrintEditor4*
        - /usr/share/metainfo/org.gtk.WidgetFactory4*
