name       : minuet
version    : 24.01.95
release    : 75
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/minuet-24.01.95.tar.xz : 64c7f88d72f4c1f2d67c4a753b77a4b308fdcdea1b501f1f6b1b0209d4a66fc6
homepage   : https://kde.org/applications/education/org.kde.minuet
license    :
    - GPL-2.0-or-later
    - GFDL-1.3-or-later
component  : multimedia.audio
summary    : KDE software for music education
description: |
    Minuet aims at supporting students and teachers in many aspects of music education, such as ear training, first-sight reading, solfa, scales, rhythm, harmony, and improvisation. Minuet makes extensive use of MIDI capabilities to provide a full-fledged set of features regarding volume, tempo, and pitch changes, which makes Minuet a valuable tool for both novice and experienced musicians.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
