name       : libkleo
version    : 24.01.95
release    : 70
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libkleo-24.01.95.tar.xz : bfa4718350d5cbcb8c11e9e2cf33301746b58a49bdbbd0cbd4d1ef6ef9fd2043
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - gpgme-qt-devel
    - kf6-kcodecs-devel
    - kf6-kcompletion-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kitemmodels-devel
    - kpimtextedit-devel
    - kf6-kwidgetsaddons-devel
    - libboost-devel
rundeps    :
    - devel :
        - gpgme-qt-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
