name       : gtk-doc
version    : 1.35.1
release    : 17
source     :
    - https://download.gnome.org/sources/gtk-doc/1.35/gtk-doc-1.35.1.tar.xz : 611c9f24edd6d88a8ae9a79d73ab0dc63c89b81e90ecc31d6b9005c5f05b25e2
homepage   : https://www.gtk.org/gtk-doc/
license    : GPL-2.0-or-later
component  : desktop.gnome.doc
summary    : GTK API Documentation generator
description: |
    GTK-Doc is a project which was started to generate API documentation from comments added to C code. It is typically used to document the public API of GTK+ and GNOME libraries, but it can also be used to document application code.
builddeps  :
    - pkgconfig(python3)
    - docbook-xml
    - itstool
    - pygments
rundeps    :
    - docbook-xml
    - pygments
    - python3
patterns   :
    - /usr/share/aclocal
    - /usr/share/pkgconfig
    - /usr/share/gtk-doc/data
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
