name       : kamera
version    : 24.01.95
release    : 71
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kamera-24.01.95.tar.xz : 9e5865d1fce75b675fc65a750e85a2210fd9818ee45bb4d7fc859792fda1d00a
homepage   : https://kde.org/applications/utilities/org.kde.kamera
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(libgphoto2)
    - kf6-kcmutils-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
