name       : libgtkmm-4
version    : 4.20.0
release    : 5
source     :
    - https://download.gnome.org/sources/gtkmm/4.20/gtkmm-4.20.0.tar.xz : daad9bf9b70f90975f91781fc7a656c923a91374261f576c883cd3aebd59c833
homepage   : https://gtkmm.org
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
optimize   :
    - lto
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gtk4)
    - pkgconfig(pangomm-2.48)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
