name       : kicad-footprints
version    : 9.0.6
release    : 18
source     :
    - https://gitlab.com/kicad/libraries/kicad-footprints/-/archive/9.0.6/kicad-footprints-9.0.6.tar.gz : 5b0584754954534d5da949239bab859631de75da8c5cdd5bd70f9decaecaf69e
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad Footprint Libraries
description: |
    The libraries are intended to be used with KiCad.
setup      : |
    %cmake
install    : |
    %make_install
