name       : kwallet-pam
version    : 5.93.0
release    : 96
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/kwallet-pam-5.93.0.tar.xz : 762fcec596b08579923bf4049e19a1d4fcb85abc8b40ad910b3354c79699d287
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libgcrypt)
    - extra-cmake-modules
    - kf6-kwallet-devel
rundeps    :
    - socat
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
