name       : gnome-session
version    : '49.1'
release    : 46
source     :
    - https://download.gnome.org/sources/gnome-session/49/gnome-session-49.1.tar.xz : 179510be373628d79be7ac5893e9d3a5ea949c08617d7d2e21de390e320df1f6
homepage   : https://gitlab.gnome.org/GNOME/gnome-session
license    : GPL-2.0-or-later
summary    :
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session.
description:
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session
component  :
    - desktop.gnome.core
    - shell : desktop.gnome
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xtrans)
    - pkgconfig(xtst)
    - docbook-xml
    - xmlto
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs
    - xdg-user-dirs-gtk
    - xdg-utils
    - shell :
        - gnome-session
        - pipewire
        - xdg-desktop-portal-gnome
patterns   :
    - shell :
        - /usr/share/xdg-desktop-portal/gnome-portals.conf
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
replaces   :
    - shell :
        - gnome-session-shell-experimental
setup      : |
    %meson_configure -Dx11=true
build      : |
    %ninja_build
install    : |
    %ninja_install
