name       : kate
version    : 24.01.95
release    : 82
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kate-24.01.95.tar.xz : 74d6dcc0b77c9f66645454c0f796d57f856fb8b51825299d9aa6cb8ea20697d6
homepage   : https://apps.kde.org/kate
license    :
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
    - MIT
component  : desktop.kde.core
summary    :
    - KDE advanced text editor
description:
    - Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
optimize   : lto
builddeps  :
    - pkgconfig(libgit2)
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - kf6-kuserfeedback-devel
    - kf6-kwallet-devel
    - kf6-syntax-highlighting-devel
    - kf6-ktexteditor-devel
    - kf6-ktextwidgets-devel
    - libplasma-devel
    - plasma-activities-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache

    # remove docs
    rm -rf $installdir/usr/share/doc

    # causes issues with appstream-builder, subpackage if you want to provide it
    rm $installdir/usr/share/metainfo/org.kde.kwrite.appdata.xml
