name       : akonadi-search
version    : 24.01.95
release    : 75
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/akonadi-search-24.01.95.tar.xz : 3019e21f7c5690e0c435de9469991dc88a6ef21905394b202ca7f2a679ed9161
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-mime-devel
    - kf6-kcalendarcore-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-kitemmodels-devel
    - kf6-krunner-devel
    - ktextaddons-devel
    - libboost-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kf6-kcalendarcore-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
