name       : calendarsupport
version    : 24.01.95
release    : 73
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/calendarsupport-24.01.95.tar.xz : 9475794ff5c994b4c1f282377789d5100105b5aeace874918affc922ffd8626f
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(Qt6Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - kf6-kcalendarcore-devel
    - kcalutils-devel
    - kf6-kcontacts-devel
    - kf6-kguiaddons-devel
    - kf6-kholidays-devel
    - kidentitymanagement-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
