name       : libgnome-menus
version    : 3.38.1
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-menus/3.38/gnome-menus-3.38.1.tar.xz : 1198a91cdbdcfb232df94e71ef5427617d26029e327be3f860c3b0921c448118
homepage   : https://gitlab.gnome.org/GNOME/gnome-menus
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME library to access and manipulate menus
description: |
    GNOME library to access and manipulate menus
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %patch -p1 -i $pkgfiles/0001-Do-not-hide-System-Settings-category.patch
    %patch -p1 -i $pkgfiles/80_file_monitor_delayed.patch
    %configure_no_runstatedir --disable-static
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc

    # Ensure legacy "applications.menu" can be found too
    ln -s /usr/share/xdg/menus/gnome-applications.menu $installdir/usr/share/xdg/menus/applications.menu
