name       : kmime
version    : 24.01.95
release    : 70
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kmime-24.01.95.tar.xz : 202f1b65b63ed2af59d17e9e4cf3808ce61e1da8c2f8c3aea65dadf4b4383d12
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kf6-kcodecs-devel
    - kf6-ki18n-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
