name       : libxml++
version    : 5.4.0
release    : 12
source     :
    - https://download.gnome.org/sources/libxml++/5.4/libxml++-5.4.0.tar.xz : e9a23c436686a94698d2138e6bcbaf849121d63bfa0f50dc34fefbfd79566848
homepage   : https://libxmlplusplus.github.io/libxmlplusplus/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C++ bindings to libxml2
description: |
    C++ bindings to libxml2
builddeps  :
    - pkgconfig(libxml-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
