# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libcinnamon-desktop
version    : 6.6.0
release    : 9
source     :
    - https://github.com/linuxmint/cinnamon-desktop/archive/refs/tags/6.6.0.tar.gz : d34bde974e3ade5106dfeb49233e3c5c7e30f84dbc4af49634feca3540990243
homepage   : https://github.com/linuxmint/cinnamon-desktop
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : The cinnamon-desktop library
description: |
    libcinnamon-desktop contains the libcinnamon-desktop library.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
