name       : akregator
version    : 24.01.95
release    : 70
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/akregator-24.01.95.tar.xz : b504101895f1320f487f420f3100b068315c848b19dd1e922476fc8499a2f34c
homepage   : https://kde.org/applications/internet/org.kde.akregator
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.news
summary    : RSS Feed Reader
description: |
    Akregator is a news feed reader for the KDE desktop. It enables you to follow news sites, blogs and other RSS/Atom-enabled websites without the need to manually check for updates using a web browser. Akregator is designed to be both easy to use and to be powerful enough to read hundreds of news sources conveniently.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kimap-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kontactinterface-devel
    - kpimtextedit-devel
    - kf6-ktexteditor-devel
    - kf6-kuserfeedback-devel
    - ktextaddons-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - kf6-syndication-devel
    - kf6-kstatusnotifieritem-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remvove doc
    rm -rf $installdir/usr/share/doc
