name       : ptyxis
version    : '49.2'
release    : 10
source     :
    - https://download.gnome.org/sources/ptyxis/49/ptyxis-49.2.tar.xz : 16d37e122fb7c0a25147e8297c959eda17b887ee1d812ddc7bcca5314309a5b3
homepage   : https://devsuite.app/ptyxis/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A terminal for a container-oriented desktop
description: |
    Ptyxis is a terminal for GNOME that focuses on ease-of-use in a world of containers.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(vte-2.91)
    - desktop-file-utils
setup      : |
    %meson_configure -Dgeneric=terminal
build      : |
    %ninja_build
install    : |
    %ninja_install
