name       : loupe
version    : '49.1'
release    : 9
source     :
    - https://download.gnome.org/sources/loupe/49/loupe-49.1.tar.xz : 30098bc979a1c87a2ecb27b4a5ab725abf900bd710bb9c2bcc0c942d515c51c5
homepage   : https://apps.gnome.org/Loupe/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : GNOME's default image viewer
description: |
    An image viewer application written with GTK 4, Libadwaita and Rust. Browse through your images and inspect their metadata with:
    - Fast GPU accelerated image rendering
    - Tiled rendering for vector graphics
    - Extendable and sandboxed image decoding
    - Accessible presentation of the most important metadata.
networking : true
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(lcms2)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libseccomp)
    - desktop-file-utils
    - itstool
    - rust
rundeps    :
    - glycin
    - webp-pixbuf-loader
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
