name       : python-pam
version    : 2.0.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/python-pam/python-pam-2.0.2.tar.gz : 97235235ba9b82dbae8068d1099508455949b275f77273ca22fdbd8b1fb5d950
homepage   : https://pypi.org/project/python-pam/
license    : MIT
component  : programming.python
summary    : Python PAM module using ctypes.
description: |
    Python PAM module using ctypes.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-six
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
