name       : kpipewire
version    : 5.93.2
release    : 12
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/kpipewire-5.93.2.tar.xz : 36a9261c486796a66fc4f2747982ea3b96cf1ff169e1416359bdfa131527a71f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Components relating to pipewire use in Plasma
description: |
    Components relating to pipewire use in Plasma
patterns   :
    - /usr/lib64/libKPipeWire*.so
    - /usr/lib64/libKPipeWireRecord*.so
optimize   : lto
builddeps  :
    - pkgconfig(KWaylandClient)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libavformat)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libva)
    - extra-cmake-modules
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
