name       : d-spy
version    : '49.2'
release    : 8
source     :
    - https://download.gnome.org/sources/d-spy/49/d-spy-49.2.tar.xz : b814ff27d828aabcda72f2c62f1b41d62035f743d06fd9a7e3c5c986c4879a69
homepage   : https://apps.gnome.org/Dspy/
license    : GPL-3.0-or-later
component  : system.utils
summary    : A D-Bus explorer for GNOME
description: |
    D-Spy is a simple tool to explore D-Bus connections.
optimize   :
    - lto
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdex-1)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
