name       : kpimtextedit
version    : 24.01.95
release    : 71
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kpimtextedit-24.01.95.tar.xz : 453566396f97e162acbb4580bdbe20fd884eb15b003a701529268d9c7da18184
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt6TextToSpeech)
    - kf6-ktexttemplate-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
    - kf6-syntax-highlighting-devel
    - ktextaddons-devel
rundeps    :
    - devel :
        - kf6-ktextwidgets-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
