name       : pokeget
version    : 1.6.7
release    : 3
source     : 
    - git|https://github.com/talwat/pokeget-rs.git : 1.6.7
homepage   : https://github.com/talwat/pokeget-rs
license    : MIT
component  : programming
summary    : A better rust version of pokeget.
description: |
    A better rust version of pokeget.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
