name       : simple-scan
version    : '49.1'
release    : 35
source     :
    - https://download.gnome.org/sources/simple-scan/49/simple-scan-49.1.tar.xz : 9ae8d4151ecaf95845eb9f99b436d579c838f2cf02763fba3bc03780251be334
homepage   : https://apps.gnome.org/SimpleScan/
license    : GPL-3.0-or-later
component  : office
summary    : Make a digital copy of your photos and documents
description: |
    A really easy way to scan both text and images. You can crop out the bad parts of an image and rotate it if it is the wrong way round. You can print your scans, export them to pdf, or save them in a range of image formats. This app uses the SANE framework to support most existing scanners.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(gusb)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libwebp)
    # pkgconfig(packagekit-glib2) future
    - pkgconfig(sane-backends)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
