name       : sddm-kcm
version    : 5.93.0
release    : 87
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/sddm-kcm-5.93.0.tar.xz : 3f91cc8d23fdc97d307f9dc7491060bdd3b2ae61aaa7ff822c542a34ddbd2a31
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kdeclarative-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
