name       : libkgapi
version    : 24.01.95
release    : 72
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libkgapi-24.01.95.tar.xz : 52436173def4d16d4e86f4daa9ab0f59435284b9ce98971def6c88a2c7bbfaae
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - kf6-kcalendarcore-devel
    - kf6-kconfig-devel
    - kf6-kcontacts-devel
    - kf6-kwallet-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
