name       : bovo
version    : 24.01.95
release    : 71
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/bovo-24.01.95.tar.xz : 54a8ddcfd563c7b8e4e79339e129a6fe52c1810f5b433f20b9e8a22250285e9b
homepage   : https://kde.org/applications/games/org.kde.bovo
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.strategy
summary    : A Gomoku like game for two players
description: |
    Bovo is a Gomoku like game for two players, where the opponents alternate in placing their respective pictogram on the game board. Also known as Connect Five, Five in a row, X and O, Naughts and Crosses.
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Svg)
    - kf6-kcompletion-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
