name       : kmailtransport
version    : 24.01.95
release    : 75
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kmailtransport-24.01.95.tar.xz : 75439582afa0c714892f793553861b027c71b227144caffcdb220cce7f70ed4f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kf6-kcalendarcore-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kio-devel
    - ksmtp-devel
    - kf6-kwallet-devel
    - libkgapi-devel
    - qtkeychain-qt6-devel
rundeps    :
    - devel :
        - kf6-kwallet-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
