name       : kompare
version    : 24.01.95
release    : 57
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kompare-24.01.95.tar.xz : 78d2a7377c91b997da7c90a9ebf959d8246cd327d64b267aec0e68e40624644e
homepage   : https://kde.org/applications/development/org.kde.kompare
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : File Comparator
description: |
    Tool to visualize changes between two versions of a file.
builddeps  :
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kparts-devel
    - kf6-ktexteditor-devel
    - libkomparediff2-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
