name       : gthumb
version    : 3.12.8.1
release    : 44
source     :
    - https://download.gnome.org/sources/gthumb/3.12/gthumb-3.12.8.1.tar.xz : 27362fc11ca5c581f31682230c95020e5a1fcddf4cffebe75557828c6174db5b
homepage   : https://gitlab.gnome.org/GNOME/gthumb/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Image viewer and browser utility
description: |
    gthumb is an application for viewing, editing, and organizing collections of images.
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord)
    - pkgconfig(exiv2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libheif)
    - pkgconfig(libjpeg)
    - pkgconfig(libjxl)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libssh)
    - pkgconfig(libwebp)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
