name       : zenity
version    : 4.2.0
release    : 25
source     :
    - https://download.gnome.org/sources/zenity/4.2/zenity-4.2.0.tar.xz : 5f983340c6fa55f4fab5a9769d0771b2cdf1365e2c158ac11cc16ffd892f6bcd
homepage   : https://gitlab.gnome.org/GNOME/zenity
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : A tool that allows you to display GTK dialog boxes in commandline and shell scripts
description: |
    A tool that allows you to display GTK dialog boxes in commandline and shell scripts.
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(libnotify)
    - help2man
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
