name       : kmbox
version    : 24.01.95
release    : 69
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kmbox-24.01.95.tar.xz : ef7e25c0da1a74ebd53e9325149dfb2bb1949c645ec562e10dd68ccf2d517caf
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - kf6-kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
