name       : kdialog
version    : 24.01.95
release    : 65
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdialog-24.01.95.tar.xz : 6510553ec55058817079bdbb28ea88477191c37f1bd1e7a40b6fc960ff10c979
homepage   : https://kde.org/applications/utilities/org.kde.kdialog
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kf6-kdbusaddons-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-ktextwidgets-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
