name       : kontactinterface
version    : 24.01.95
release    : 70
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kontactinterface-24.01.95.tar.xz : 75b7eb9893fc72ca7b1ad76f5f2ac3aa7dd1527077507f94a605cbdd677f5033
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt6DBus)
    - pkgconfig(x11)
    - kf6-kparts-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
