name       : kimap
version    : 24.01.95
release    : 69
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kimap-24.01.95.tar.xz : eaa6cfa379aa38599c3ff503c324fbc7eec4425278dc9cd467eff2939b760b72
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(libsasl2)
    - kmime-devel
    - kf6-kio-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
