name       : alacarte
version    : 3.58.0
release    : 19
source     :
    - https://download.gnome.org/sources/alacarte/3.58/alacarte-3.58.0.tar.xz : 3f4eb9370a9cd97547ec2f182d091f59315eea5ed335cc8243d4df2354862d52
homepage   : https://gitlab.gnome.org/GNOME/alacarte/
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME Menu Editor
description: |
    GNOME Graphical Menu Editor
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - libgnome-menus
    - python-gobject
setup      : |
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
