name       : discover
version    : 6.5.1
release    : 46
source     :
    - https://download.kde.org/stable/plasma/6.5.1/discover-6.5.1.tar.xz : 7ae515a9ad35dd6db568ec23dc5ec6c24c1c555ddf412f041ede4be9dcf3f3cc
homepage   : https://apps.kde.org/discover/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Discover helps you find and install applications, games, and tools.
description: |
    Discover helps you find and install applications, games, and tools. You can search or browse by category, and look at screenshots and read reviews to help you pick the perfect app. With Discover, you can manage software from multiple sources, including your operating system's software repository, Flatpak repos, the Snap store, or even AppImages from store.kde.org. Finally, Discover also allows you to find, install, and manage add-ons for Plasma and all your favorite KDE apps!
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6WebView)
    - pkgconfig(flatpak)
    - pkgconfig(fwupd)
    - pkgconfig(libmarkdown)
    - pkgconfig(packagekitqt6)
    - appstream-qt6-devel
    - kf6-attica-devel
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcolorscheme-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kuserfeedback-devel
    - kf6-purpose-devel
    - kirigami-addons-devel
    - qcoro-qt6-devel
rundeps    :
    - appstream-catalog
    - kf6-kirigami
    - kf6-kitemmodels
    - kf6-purpose
    - kf6-qqc2-desktop-style
    - kirigami-addons
clang      : true
optimize   : thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-Allow-notifier-to-autostart-on-all-editions.patch
    %patch -p1 -i $pkgfiles/port-to-kirigamiapp.patch

    %cmake_kf6 -DPACKAGEKIT_AUTOREMOVE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove docs
    rm -rfv $installdir/usr/share/doc

    # Duplicate with flatpak-kcm
    rm -v $installdir/usr/share/icons/hicolor/scalable/apps/flatpak-discover.svg
