name       : evolution-data-server
version    : 3.58.1
release    : 111
source     :
    - https://download.gnome.org/sources/evolution-data-server/3.58/evolution-data-server-3.58.1.tar.xz : a914928814ef887f0979ba78ea8d7bcc98f96cf07cbb70b0051980bd90ec35f0
homepage   : https://gitlab.gnome.org/GNOME/evolution-data-server
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(icu-uc)
    - pkgconfig(ldap)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.1)
    - pkgconfig(webkitgtk-6.0)
    - db5-devel
    - gperf
    - libphonenumber-devel
    - vala
setup      : |
    %cmake_ninja \
        -DENABLE_GTK4=ON \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DENABLE_WEATHER=ON \
        -DSYSCONF_INSTALL_DIR="/usr/share" \
        -DWITH_KRB5=OFF \
        -DWITH_PHONENUMBER=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

