name       : metacity
version    : 3.58.1
release    : 21
source     :
    - https://download.gnome.org/sources/metacity/3.58/metacity-3.58.1.tar.xz : e430c8a92409ef2f91a4dabd50a71e3d3bbcc474a3dec1caec3813b381d7d1b0
homepage   : https://gitlab.gnome.org/GNOME/metacity/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - pkgconfig(xpresent)
    - pkgconfig(xres)
setup      : |
    %patch -p1 -i $pkgfiles/0001-revert-window-stop-updating-layers.patch
    %patch -p1 -i $pkgfiles/0002-window-remove-obsolete-comments.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
