name       : kdenlive
version    : 24.01.95
release    : 95
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdenlive-24.01.95.tar.xz : 45bdfa9863681ffccaf14d4ea812fc95a7d9dc76f030a1d450115bdf8666420c
homepage   : https://kdenlive.org
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Video editing application, based on MLT Framework and KF5
description: |
    Video editing application, based on MLT Framework and KDE Frameworks 5.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6MultimediaWidgets)
    - pkgconfig(Qt6NetworkAuth)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - pkgconfig(libv4l2)
    - pkgconfig(mlt-framework-7)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
    - kf6-purpose-devel
rundeps    :
    - breeze
    - breeze-icons
    - dvgrab
    - frei0r
    - qt6-quickcontrols
    - qt6-quickcontrols2
setup      : |
    %patch -p1 -i $pkgfiles/0001-Unset-QPA_PLATFORMTHEME-to-prevent-starting-with-gtk.patch
    %patch -p1 -i $pkgfiles/0001-Add-StartupWMClass-to-desktop-file.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove doc
    rm -rf $installdir/usr/share/doc
