name       : plasma-vault
version    : 5.93.0
release    : 64
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/plasma-vault-5.93.0.tar.xz : 4fa61194bf1f63bc2642ca8b98a6e857f96be86a1831dfd8275ffb0f6b26a71a
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt6Quick)
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kitemmodels-devel
    - kf6-kpackage-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
