name       : evolution-ews
version    : 3.58.1
release    : 66
source     :
    - https://download.gnome.org/sources/evolution-ews/3.58/evolution-ews-3.58.1.tar.xz : 10006bd78ffb7d6409c5d00a558be9dc190e8594bb9a2b973e2ec05613167820
homepage   : https://gitlab.gnome.org/GNOME/evolution/-/wikis/home
license    : LGPL-2.1-or-later
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-1.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
