name       : file-roller
version    : '44.6'
release    : 50
source     :
    - https://download.gnome.org/sources/file-roller/44/file-roller-44.6.tar.xz : 9e873b5005bc425799a8cd4b237e1fff430ec8d6b34a992c6033f1dfc6e3764e
homepage   : https://gitlab.gnome.org/GNOME/file-roller/
license    : GPL-2.0-or-later
summary    : Archive manager for the GNOME desktop environment
description: |
    File Roller is an archive manager for the GNOME environment.  This means that you can create and modify archives; view the content of an archive; view and modify a file contained in the archive; extract files from the archive.
component  : desktop.gnome
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libarchive)
    - pkgconfig(libnautilus-extension-4)
    - pkgconfig(libportal-gtk4)
    - desktop-file-utils
    - itstool
rundeps    :
    - unrar
setup      : |
    %meson_configure -Dpackagekit=false -Duse_native_appchooser=true
build      : |
    %ninja_build
install    : |
    %ninja_install
