name       : kontact
version    : 24.01.95
release    : 71
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kontact-24.01.95.tar.xz : 74aeb2a99c2daa0a25050dbe698fc965dbe0387b3b5ca69e224babb58fad6b37
homepage   : https://kde.org/applications/office/org.kde.kontact
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Container application to unify several major PIM applications within one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kcontacts-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kmime-devel
    - kontactinterface-devel
    - kf6-kparts-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - knotes
    - korganizer
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
