name       : libshumate
version    : 1.5.1
release    : 17
source     :
    - https://download.gnome.org/sources/libshumate/1.5/libshumate-1.5.1.tar.xz : daadf8b700134388c7e933e0b623586aaa7f2fbe8b3a6259387513303b9876e6
homepage   : https://gitlab.gnome.org/GNOME/libshumate
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Shumate is a GTK toolkit providing widgets for embedded maps.
description: |
    Shumate is a GTK toolkit providing widgets for embedded maps.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(sysprof-capture-4)
    - gperf
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
