name       : mailcommon
version    : 24.01.95
release    : 75
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/mailcommon-24.01.95.tar.xz : 3f32af3357978af494650de438c7e55c60abcc9f60074153c7f21cfc55f6dffd
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(Qt6WebEngineWidgets)
    - pkgconfig(phonon4qt6)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kf6-kcontacts-devel
    - kf6-kdbusaddons-devel
    - kdesignerplugin-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - kmailtransport-devel
    - ktextaddons-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - kf6-syntax-highlighting-devel
rundeps    :
    - devel :
        - akonadi-mime-devel
        - libkdepim-devel
        - libkleo-devel
        - messagelib-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
