name       : akonadi-calendar
version    : 24.01.95
release    : 74
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/akonadi-calendar-24.01.95.tar.xz : 2a4978bd356c31763e066d7a4925a7af441102eb448207c2ba2c57d9c5fae542
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kf6-kcalendarcore-devel
    - kcalutils-devel
    - kf6-kcontacts-devel
    - kf6-kdbusaddons-devel
    - kidentitymanagement-devel
    - kf6-kio-devel
    - kmailtransport-devel
    - kf6-knotifications-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - kf6-kwallet-devel
    - kf6-kxmlgui-devel
    - libkdepim-devel
    - libkleo-devel
    - messagelib-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kf6-kcalendarcore-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
