name       : plasma-disks
version    : 5.93.0
release    : 37
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/plasma-disks-5.93.0.tar.xz : 116def373c1fe16ea4bcd7a721405553990937aeee311a78401ad9bd0c61a027
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-3.0-only
    - LGPL-3.0-only
component  : system.utils
summary    : Monitors S.M.A.R.T. capable devices for imminent failure
description: |
    Monitors S.M.A.R.T. capable devices for imminent failure
optimize   : lto
builddeps  :
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kpackage-devel
    - smartmontools-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
