name       : kaccounts-providers
version    : 24.01.95
release    : 63
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kaccounts-providers-24.01.95.tar.xz : db01e5869a17f2b2414e71c65b1ba90f42696287bba7e151117b37b03e66f8fe
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt6)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kf6-kdeclarative-devel
    - kf6-kio-devel
    - kf6-kpackage-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
