name       : unrar
version    : 7.2.1
release    : 48
source     :
    - https://www.rarlab.com/rar/unrarsrc-7.2.1.tar.gz : 3fe3b4d710da45521625353dc2e023dad48c010f02a93302756e1061a8f3ae8e
homepage   : https://www.rarlab.com
license    : Distributable
component  : system.utils
summary    : RAR decompression program
description: |
    RAR decompression program
setup      : |
    %patch -p1 -i $pkgfiles/0001-Fix-amateur-hour-shit.patch
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
