name       : kactivitymanagerd
version    : 5.93.0
release    : 91
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/kactivitymanagerd-5.93.0.tar.xz : b407e083f6a408d56f4b8293d8d12b71f1908b4986f052a240a5303d41cb5875
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
optimize   : lto
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
