name       : libkeduvocdocument
version    : 24.01.95
release    : 72
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libkeduvocdocument-24.01.95.tar.xz : ef6bed5ef9fb46faf28c30e4997ec05030472450321d8cd8850656976234a46a
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Xml)
    - kf6-karchive-devel
    - kf6-kio-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
