name       : akonadi-notes
version    : 24.01.95
release    : 69
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/akonadi-notes-24.01.95.tar.xz : 01f837c21593b19bf160745518d0861ed616a79da0c080bcfb1c96f869fde06b
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - kf6-kcodecs-devel
    - kf6-ki18n-devel
    - kmime-devel
    - libboost-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
