name       : partitionmanager
version    : 24.01.95
release    : 41
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/partitionmanager-24.01.95.tar.xz : 6772041936587d53c01fc5bbc1d845201f34efbe1ca42f421ce6f863cae258a0
homepage   : https://apps.kde.org/partitionmanager/
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(libatasmart)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - kpmcore-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove HTML docs
    rm -rf $installdir/usr/share/doc
