name       : kget
version    : 24.01.95
release    : 69
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kget-24.01.95.tar.xz : 84a608b01e1391b8249bb175178a39a780f852d29ac11504d3bce5ebb54f629b
homepage   : https://kde.org/applications/internet/org.kde.kget
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libmms)
    - gpgme-qt-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-kparts-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kwallet-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
    - qca-qt6-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
