name       : keysmith
version    : 24.01.95
release    : 3
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/keysmith-24.01.95.tar.xz : 3df40756e7b6e868558c5fc5c8084ec87eb602ae8cc1a7705640e0d010779e0c
homepage   : https://apps.kde.org/keysmith
license    : GPL-3.0-or-later
component  : desktop.kde
summary    : OTP client for Plasma Mobile and Desktop
description: |
    Keysmith is an application to generate two-factor authentication (2FA) tokens when logging in to your (online) accounts. Currently it supports both HOTP and TOTP tokens.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - pkgconfig(libsodium)
    - extra-cmake-modules
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-kwindowsystem-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
