name       : kcharselect
version    : 24.01.95
release    : 63
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kcharselect-24.01.95.tar.xz : 76ed4a26d899ded09e9e62e7841c357d137600620b3462939b7345fd5772576d
homepage   : https://kde.org/applications/utilities/org.kde.kcharselect
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Character Selector
description: |
    KCharSelect is a tool to select special characters from all installed fonts and copy them into the clipboard.
optimize   : lto
builddeps  :
    - kf6-kbookmarks-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kxmlgui-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
