name       : palapeli
version    : 24.01.95
release    : 56
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/palapeli-24.01.95.tar.xz : e172466070d709e24d997844485703e662050ab72ff3e410900810b9d508ebc1
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6Widgets)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
