name       : ksshaskpass
version    : 5.93.0
release    : 90
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/ksshaskpass-5.93.0.tar.xz : 3d4614aa6bfab05dd7ff554401614912c6fb340bca703db4d383a6df8b547249
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
optimize   : lto
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kwallet-devel
    - kf6-kwidgetsaddons-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
