name       : libksysguard
version    : 5.93.0
release    : 92
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/libksysguard-5.93.0.tar.xz : f3120fb53128877ff32fe6a11d7d8077c023faac024371b09f5faa1d08bf1369
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
optimize   : lto
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(Qt6WebEngineWidgets)
    - pkgconfig(xres)
    - kf6-kauth-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - lm_sensors-devel
    - libplasma-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
