name       : orca
version    : '49.4'
release    : 38
source     :
    - https://download.gnome.org/sources/orca/49/orca-49.4.tar.xz : b6ba4cc5878411c34a7d5b7ee9b2c5c9b1d04add10bfd20f6e2331d594165207
homepage   : https://gitlab.gnome.org/GNOME/orca
license    : LGPL-2.1-or-later
component  : desktop.gnome
summary    : Orca Screen Reader
description: |
    Orca is a free, open source, flexible, and extensible screen reader that provides access to the graphical desktop via user-customizable combinations of speech and/or braille.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(speech-dispatcher)
    - itstool
    - python-dasbus
    - yelp-tools
rundeps    :
    - pyatspi2
    - python-dasbus
    - speech-dispatcher
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
