name       : kgeography
version    : 24.01.95
release    : 73
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kgeography-24.01.95.tar.xz : 93129e15a3d40933c399c7c629bf3985e5f6782534569b1e30c7dbed04558371
homepage   : https://kde.org/applications/education/org.kde.kgeography
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-kiconthemes-devel
    - kf6-kxmlgui-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
