name       : gnome-sudoku
version    : '49.2'
release    : 28
source     :
    - https://download.gnome.org/sources/gnome-sudoku/49/gnome-sudoku-49.2.tar.xz : ca670fac73d9e5c3e7833fda3556710b4220db6433e7bec50a710560da7db840
homepage   : https://gitlab.gnome.org/GNOME/gnome-sudoku/-/wikis/home
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku - The popular Japanese logic puzzle
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005. This is a logic-based number-placement puzzle in which a 9×9 square must be filled with the correct digits.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(qqwing)
    - blueprint-compiler
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
