name       : ksystemstats
version    : 5.93.0
release    : 27
source     :
    - https://download.kde.org/unstable/plasma/5.93.0/ksystemstats-5.93.0.tar.xz : 8356436cd1cad22559e48fd0f46c497437e395d67b252188bc0a3800fc329c30
homepage   : https://invent.kde.org/plasma/ksystemstats
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnm)
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - lm_sensors-devel
rundeps    :
    - libksysguard
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
