name       : pimcommon
version    : 24.01.95
release    : 74
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/pimcommon-24.01.95.tar.xz : 5ea0ff97cf644a21182ed41a542afb6798d2fde4621481fd92df3c2eb038a8a8
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - kf6-karchive-devel
    - kf6-kcalendarcore-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kldap-devel
    - kf6-kio-devel
    - kimap-devel
    - kf6-knewstuff-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - libkdepim-devel
    - kf6-purpose-devel
rundeps    :
    - devel :
        - kimap-devel
        - akonadi-contacts-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
