name       : mailimporter
version    : 24.01.95
release    : 68
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/mailimporter-24.01.95.tar.xz : 87fe9a7e0e4ca6074459be1dafed3c876ea848f15b722f2539f0e2721afcc8ea
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kf6-karchive-devel
    - kf6-kcontacts-devel
    - kimap-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - kf6-karchive-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
