name       : libksieve
version    : 24.01.95
release    : 70
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/libksieve-24.01.95.tar.xz : 7ba98cc531014b9bbb9ff234dc9fc723f829fbdc36152b4bf5bd864afff491c4
homepage   : https://kde.org/
license    : GPL-2.0-only
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt6WebEngineCore)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kf6-kio-devel
    - kmailtransport-devel
    - kmime-devel
    - kf6-knewstuff-devel
    - ktextaddons-devel
    - kf6-kwallet-devel
    - libkdepim-devel
    - pimcommon-devel
    - kf6-syntax-highlighting-devel
rundeps    :
    - devel :
        - kf6-syntax-highlighting-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
