name       : baloo-widgets
version    : 24.01.95
release    : 71
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/baloo-widgets-24.01.95.tar.xz : d62c54815b771f834fde63d6d8047f7af495ee1675afe1824122c07dc199a85d
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - kf6-baloo-devel
    - kf6-kio-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
