name       : appstream-catalog
version    : '20251031'
release    : 25
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz: 68c8dffb88203f418518e5cddb3d5f9f2beb3bcd60b67be92f68bd08b0a7266f
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz: 94ae9aeef26fdf5eed86351abfcd707bbc0bfa7c354b81c9ee64eabef60fec49
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz: a44864338bdd7f7b14a9bc517bfefc68882e008b55023dca37e687186c22e903
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz: 690601d473d8bb8fd4de72f7155fbda6db4670c793be961af4ff0ce4c82ebb6f
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz: 77dc6956ada7894e761a3a5c487db16ede23c98b3ae017cb77c9d7e653298ffa
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz: 3bc505607a492f20441345c0bff05a03f7cc32ac8ae4063349d950856443d150
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz: a1933c340d15b070179920e8fdf6dd01f9dee9b60bb4d697994053dd425c770f
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : false
install    : |
    install -Dm00644 $sources/Components-x86_64.xml.gz $installdir/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf $sources/icons-48x48.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf $sources/icons-48x48@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf $sources/icons-64x64.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf $sources/icons-64x64@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf $sources/icons-128x128.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf $sources/icons-128x128@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2
replaces   : appstream-data
