name       : ksmtp
version    : 24.01.95
release    : 65
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/ksmtp-24.01.95.tar.xz : f63151f3a6c6327be4fffa40aace6ebadf75e6fd6aac945a3249fb5583a94c09
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kf6-kio-devel
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
