name       : kdeconnect
version    : 24.01.95
release    : 67
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.95/src/kdeconnect-kde-24.01.95.tar.xz : 1143e6bbb7ae8db35a5d7a62e3b98ce99dbd184124259e2813e42986da42c586
homepage   : https://kdeconnect.kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(KF5WaylandClient)
    - pkgconfig(ModemManager)
    - pkgconfig(Qt6Bluetooth)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(fuse)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kpackage-devel
    - kf6-kpeople-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-modemmanager-qt-devel
    - kf6-qqc2-desktop-style-devel
    - kirigami-addons-devel
    - kpeople-devel
    - kpeoplevcard-devel
    - libfakekey-devel
    - plasma-wayland-protocols-devel
    - pulseaudio-qt-devel
    - qca-qt6-devel
rundeps    :
    - kf6-kirigami
    - kpeoplevcard
    - sshfs-fuse
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache

    # remove doc
    rm -rf $installdir/usr/share/doc
